### ISSUE TITLE
Глобальные пути в Speech-to-Text-Russian/model/conf/ivector_extractor.conf

### ISSUE THREAD

**Issue by sergeyerr** [SergeyShk/Speech-to-Text-Russian#10]
Добрый день!
Можете исправить глобальные пути в ivector_extractor.conf(или хотя бы прописать это в инструкции), а то без их правки невозможно запустить start_recognition.py

<em>
--splice-config=/speech_recognition/model/conf/splice.conf
--cmvn-config=/speech_recognition/model/conf/online_cmvn.conf
--lda-matrix=/speech_recognition/model/ivector_extractor/final.mat
--global-cmvn-stats=/speech_recognition/model/ivector_extractor/global_cmvn.stats
--diag-ubm=/speech_recognition/model/ivector_extractor/final.dubm
--ivector-extractor=/speech_recognition/model/ivector_extractor/final.ie
--num-gselect=5
--min-post=0.025
--posterior-scale=0.1
--max-remembered-frames=1000
--max-count=100
</em>

**Comment by SergeyShk** [comment]
Спасибо за исправление.
