### ISSUE TITLE
ERROR 	 Не удалось распарсить транскрибацию файла 'example.wav'

### ISSUE THREAD

**Issue by AldiyarUaliev** [SergeyShk/Speech-to-Text-Russian#12]
![image](https://user-images.githubusercontent.com/43777543/80902594-f74ba600-8d33-11ea-91b7-45de5771aae7.png)
Выходит такая ошибка. сегодня получил последний комит, модель обновил как в инструкции запустил. Помогите пожалуйста
![image](https://user-images.githubusercontent.com/43777543/80903796-4e517b00-8d34-11ea-9333-4a6aa76645e3.png)

**Comment by SergeyShk** [comment]
Что лежит в папке "ass"? С парсингом попробую разобраться.

**Comment by AldiyarUaliev** [comment]
> Что лежит в папке "ass"? С парсингом попробую разобраться.
вот 
![image](https://user-images.githubusercontent.com/43777543/80916383-1d943480-8d7a-11ea-9130-7fdb6956e31a.png)

**Comment by SergeyShk** [comment]
Обновил скрипты. Попробуйте сейчас пересобрать контейнер.

**Comment by AldiyarUaliev** [comment]
> Обновил скрипты. Попробуйте сейчас пересобрать контейнер.
я сменил тот исправленны файл. пересобрал, не получилось

**Comment by SergeyShk** [comment]
Исправил баг при парсинге транскрибаций, проверьте.
Также можно попробовать запускать транскрибацию без ключа -l.

**Comment by AldiyarUaliev** [comment]
Все спасибо большое. решили проблему!
