### ISSUE TITLE
Добавить в PATH пути к компонентам kaldi

### ISSUE THREAD

**Issue by TheRaiv** [SergeyShk/Speech-to-Text-Russian#18]
Доброго дня!
Не совсем понимаю, как добавить в PATH пути к компонентам kaldi. Подскажите пожалуйста как правильно это сделать

**Comment by SergeyShk** [comment]
Здравствуйте.
В руководстве приведен пример команды:

`PATH=/kaldi/src/featbin:/kaldi/src/ivectorbin:/kaldi/src/online2bin:/kaldi/src/rnnlmbin:/kaldi/src/fstbin:$PATH`

В интернете можно найти другие способы по запросу "added a path to PATH".

**Comment by TheRaiv** [comment]
Спасибо, вроде разобрался

**Comment by TheRaiv** [comment]
Спасибо, вроде разобрался.
После создания docker-образа столкнулся со следующей проблемой... подскажите пожалуйста 
Error response from daemon: create asr_volume: missing required option: "type"
![Screenshot_2](https://user-images.githubusercontent.com/25856459/97564045-8bae7100-1a16-11eb-9736-a613f15886d9.png)

**Comment by SergeyShk** [comment]
Добавьте опцию type:
`-o type=tmpfs`
или
`-o type=btrfs`

**Comment by TheRaiv** [comment]
Спасибо, это определенно помогло.
Далее при запустить docker-контейнера возникает ошибка при установке тома. Подскажите в чем может быть причина?
![Screenshot_3](https://user-images.githubusercontent.com/25856459/97623812-c6d19400-1a58-11eb-99c6-58c862d596e4.png)

**Comment by SergeyShk** [comment]
Так вместо [DIR] нужно указывать Вашу локальную папку, куда будет примонтирован том.

**Comment by TheRaiv** [comment]
Извините, а о какой локальной папке идет речь? Пробовал по-разному заменить [DIR], к примеру -o device=/home/user/test , при попытке запустить docker-контейнер ошибка остается прежней...

**Comment by SergeyShk** [comment]
Создайте новый том (не asr_volume), указав путь к существующей локальной папке, куда он будет примонтирован (например, -o device=/home/user/test) и запустите контейнер. Такой же ошибки быть не может.

**Comment by TheRaiv** [comment]
У меня не вышло разобраться с докером, попробую создать новую виртуалку. Я вам благодарен за ваши советы, спасибо. Скажите пожалуйста, какую pykaldi лучше устанавливать (с поддержкой GPU или без? Или лучше из исходников? Или это все вместе?). И еще момент, возможна ли встреча с вами онлайн (например в дискорде)? Боюсь без вашей помощи и подсказок не разберусь в этом. В долгу не останусь.

**Comment by SergeyShk** [comment]
В воскресенье можно в зуме обсудить в любое время. Напишите мне на почту, когда удобно будет.
