### ISSUE TITLE
Ничего не происходит после вызова start_recognition.py

### ISSUE THREAD

**Issue by vovkapultik** [SergeyShk/Speech-to-Text-Russian#19]
Установил с помощью Docker, в качестве [DIR] при установке указал home/{user}/ASR
Папка при этом осталась пустой. Добавил в неё archive, в него input и output директории, но при вызове в Docker ./start_recognition.py [WAV_DIR] [OUT_DIR] ничего не выводится и процесс завершается
Подскажите, как это можно пофиксить, или, возможно, есть готовая виртуалка с поднятым приложением?

**Comment by SergeyShk** [comment]
Положите аудио-файлы непосредственно в папку home/{user}/ASR. Никакие другие папки внутри создавать не нужно.

**Comment by vovkapultik** [comment]
какие тогда указывать папки для ввода-вывода?

**Comment by vovkapultik** [comment]
Всё получилось, указал просто archive/, для вывода /archive/output
спасибо за оперативный ответ!

**Comment by vovkapultik** [comment]
ERROR: FstHeader::Read: Bad FST header: model/HCLG.fst
ERROR: Не удалось выполнить распознавание файла 'example.1-2-0000078-0000700.wav' (2020-11-18 13:29:30,899)
ERROR:logger:Не удалось выполнить распознавание файла 'example.1-2-0000078-0000700.wav'

Появилась такая проблема
