### ISSUE TITLE
алгоритм работы распознавания 

### ISSUE THREAD

**Issue by slavak688** [SergeyShk/Speech-to-Text-Russian#25]
Приветствую! Не могли бы вы помочь? Я только начал работу с kaldi и попытался сделать голосовое управление роботом ардуино используя ваш проект, но мне непонятен алгоритм распознавания речи. На сайте калди я нашел математическую часть алгоритма, но не алгоритм в общем виде( имеется ввиду что-то вроде блок схемы какой пункт за каким выполняется). Может вы знаете где найти что-то подобное или на пальцах сможете написать шаги алгоритма? Заранее спасибо

**Comment by SergeyShk** [comment]
Привет. Основой модели является так называемый HCLG-граф. Он генерируется следующим образом:
- формируется лексикон (L) из файла lexicon.txt;
- генерируется грамматическая модель (G) из файла words.txt;
- фонемы отображаются на слова (L+G);
- добавляется контекст (C+LG);
- генерируется HMM-автомат (Ha);
- собирается граф (Ha + CLG);
- выполняется обратный проход по графу (HCLG).

**Comment by slavak688** [comment]
Спасибо!
 
 
--
Слава Кузнецов

**Comment by slavak688** [comment]
А вы не подскажете какие параметры выделяются из речевого сигнала? Там же должна быть по идее огибающая, частота перехода через 0 например.
 
 
--
Слава Кузнецов

**Comment by SergeyShk** [comment]
Обычно используют MFCC или Mel-спектрограммы.
