### ISSUE TITLE
pip install не находит pykaldi

### ISSUE THREAD

**Issue by LightTemplar** [SergeyShk/Speech-to-Text-Russian#3]
pip install не находит pykaldi, этого проекта нет на pypi.org.
Подойдет ли вместо него py-kaldi-asr?

**Comment by americanexplorer13** [comment]
прочитайте внимательнее описание установки, библиотеки PyKaldi нет как таковой (ее точно нет в PyPl откуда я так понимаю pip берет пакеты), поэтому автор прописал как нужно ставить Kaldi.

**Comment by LightTemplar** [comment]
@americanexplorer13, в описании установки нет информации о том, как ставить pykaldi, зато есть `pip install -r requirements.txt` - я очень внимательно изучил это описание.

**Comment by americanexplorer13** [comment]
![wad](https://user-images.githubusercontent.com/57260643/73816671-d0a4ce80-481b-11ea-9deb-00209eb0bc4e.PNG) тут указано что kaldi нужно ставить с сайта и затем добавить его вручную в PATH

**Comment by LightTemplar** [comment]
И что, pykaldi есть в составе kaldi? Если я возьму kaldi из репозитория - pykaldi должен установиться?
Если что - у меня он не появился после сложного пошагового билдинга всего проекта kaldi согласно их инструкции.

**Comment by LightTemplar** [comment]
У меня нет проблемы установить kaldi - он установлен. 
У меня проблема установить этот проект, поскольку он требует pykaldi в requirements.txt, но не объясняет, где его брать. И я банально шаг 2 не могу выполнить из-за этого.
Установки conda я вообще хотел бы избежать. Можно ли как-то поставить pykaldi ещё? Можно ли использовать какие-то альтернативы?
Об этом, собственно, и был создан этот issue.

**Comment by americanexplorer13** [comment]
Так смотрите, в самих питоновских файлах импорта библиотеки pykaldi нет, есть только kaldi который я так понимаю добавляется с помощью прописывания PATH. Попробуйте просто проигнорировать requirements.txt либо его вообще оттуда убрать и запустить проект если вы уже добавили в PATH Kaldi.

**Comment by SergeyShk** [comment]
Убрал pykaldi из requirements, обновил руководство по установке.
Если принципиально не хочется ставить conda, то pykaldi можно собрать самому:

> git clone https://github.com/pykaldi/pykaldi.git
> cd pykaldi
> 
> == Ubuntu
> sudo apt-get install autoconf automake cmake curl g++ git graphviz \
>     libatlas3-base libtool make pkg-config subversion unzip wget zlib1g-dev
> 
> == macOS
> brew install automake cmake git graphviz libtool pkg-config wget
> 
> pip install --upgrade pip
> pip install --upgrade setuptools
> pip install numpy pyparsing
> pip install ninja
> 
> git clone -b pykaldi https://github.com/pykaldi/clif
> git clone -b pykaldi https://github.com/pykaldi/kaldi
> 
> cd tools
> ./check_dependencies.sh 
> ./install_protobuf.sh
> ./install_clif.sh
> ./install_kaldi.sh
> cd ..
> 
> python setup.py install
> 
> python setup.py test
