### ISSUE TITLE
Убрать из раздела requirements.txt поле "pykaldi"

### ISSUE THREAD

**Issue by americanexplorer13** [SergeyShk/Speech-to-Text-Russian#4]
Стоит его убрать либо переписать способ установки потому что люди путаются, пытаются ставить библиотеку которой не существует. Точнее библиотека то существует, только поставить через pip не получится, только через Conda.

**Comment by LightTemplar** [comment]
Да, стоит добавить информацию о том, откуда брать pykaldi. Если нужна conda - значит, об этом тоже рассказать.

**Comment by SergeyShk** [comment]
Убрал pykaldi из requirements, обновил руководство по установке.
