### ISSUE TITLE
Ошибка в 4 пункте по установке репозитория

### ISSUE THREAD

**Issue by americanexplorer13** [SergeyShk/Speech-to-Text-Russian#5]
нужно добавить знак равно: $ PATH=/kaldi/src/featbin:/kaldi/src/ivectorbin:/kaldi/src/online2bin:/kaldi/src/rnnlmbin:/kaldi/src/fstbin:$PATH (могу ошибаться так как не дикий линуксоид но как я увидел на Ubuntu и Debian команда PATH прописывается именно со знаком равно)

**Comment by SergeyShk** [comment]
Данная запись тоже корректна.
