### ISSUE TITLE
Ошибка при распознавании .wav

### ISSUE THREAD

**Issue by americanexplorer13** [SergeyShk/Speech-to-Text-Russian#6]
![awd](https://user-images.githubusercontent.com/57260643/74131884-f402bb80-4c17-11ea-83d1-4b3d58b79a93.PNG)
![awfasd](https://user-images.githubusercontent.com/57260643/74131890-f5cc7f00-4c17-11ea-8238-ce9409e6e271.PNG)

прилагаю две пикчи с проблемой.

**Comment by SergeyShk** [comment]
Проблема вероятно в файле. Модель не может ничего из него извлечь и сегментировать. Он либо очень шумный, либо вообще пустой.

**Comment by ankkk** [comment]
Такая же проблема, проблема явно связана не с файлом

**Comment by SergeyShk** [comment]
Попробуйте в файле utils.py изменить эту строку:
`soundfile.write(wav, wav_file, sr, format='WAV')`
на:
`soundfile.write(wav, wav_file.T, sr, format='WAV')`
