### ISSUE TITLE
Internal Server Error при попытке распознавания

### ISSUE THREAD

**Issue by gugameiru** [SergeyShk/Speech-to-Text-Russian#8]
Запустил app.py, зашел через браузер на 0.0.0.0:5000. Страница работает, файл выбирается. После нажатия на кнопку "загрузить" линукс браузер немного думает, потом выдает страницу: Internal Server error: The server encountered an internal error and was unable to complete your request. При этом в консоли линукса такой вывод (последние строчки): FileNotFoundError: [Errno 2] File data/new_house_1600/new_house_1600 does not exist Никаких служебных сообщений на странице, типа "Идет распознавание" нет, он просто открывает эту страницу с ошибкой. Как заставить заработать сервер?

**Comment by AldiyarUaliev** [comment]
> Запустил app.py, зашел через браузер на 0.0.0.0:5000. Страница работает, файл выбирается. После нажатия на кнопку "загрузить" линукс браузер немного думает, потом выдает страницу: Internal Server error: The server encountered an internal error and was unable to complete your request. При этом в консоли линукса такой вывод (последние строчки): FileNotFoundError: [Errno 2] File data/new_house_1600/new_house_1600 does not exist Никаких служебных сообщений на странице, типа "Идет распознавание" нет, он просто открывает эту страницу с ошибкой. Как заставить заработать сервер?

решили проблему?

**Comment by gugameiru** [comment]
В каком-то смысле решил - более корректно скомпилировал Kaldi (я оказывается запускал make один раз, а надо три раза в разных местах:) и затем запускал распознавание из русскоязычной модели - там есть команда decode.sh, отлично работает. А что касается конкретно этого сервиса Speech-To-Text - автор советует docker контейнер использовать, там все настроено у него, но я с докером никогда не работал, поэтому пробовать не стал. Так что наверное закрою ветку.
